import { createId } from '../utils/id.js';

function createSessionExercise(exercise = {}) {
  return {
    exerciseId: exercise.exerciseId || '',
    exerciseSource: exercise.exerciseSource || 'api',
    name: exercise.name || '',
    bodyPart: exercise.bodyPart || '',
    target: exercise.target || '',
    equipment: exercise.equipment || '',
    plannedSets: exercise.plannedSets || 3,
    plannedReps: exercise.plannedReps || 10,
    notes: exercise.notes || '',
  };
}

export const DAY_OF_WEEK = {
  MONDAY: 0,
  TUESDAY: 1,
  WEDNESDAY: 2,
  THURSDAY: 3,
  FRIDAY: 4,
  SATURDAY: 5,
  SUNDAY: 6,
};

export const DAY_NAMES = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];

export function createSession(input = {}) {
  return {
    id: input.id || createId(),
    routineId: input.routineId || '',
    name: input.name || '',
    dayOfWeek: input.dayOfWeek ?? null,
    order: input.order ?? null,
    isAutoGenerated: Boolean(input.isAutoGenerated),
    exercises: Array.isArray(input.exercises)
      ? input.exercises.map((exercise) => createSessionExercise(exercise))
      : [],
    createdAt: input.createdAt || Date.now(),
    updatedAt: input.updatedAt || Date.now(),
  };
}
